language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.0.0

services:
  - docker

script:
  # Run unit tests
  - dotnet restore
  - cd test/Gen8.Ledger.Web.Tests/
  - dotnet test

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    cd .. && cd ..;
#    docker login --email=_ --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com;
#    docker build -t rafaelturon/blockchain-investments .;
#    docker tag rafaelturon/blockchain-investments registry.heroku.com/blockchain-investments/web;
#    docker push registry.heroku.com/blockchain-investments/web;
#    fi

#docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#docker push USER/REPO;

#  - popd
#language: node_js
#node_js:
#  - 'stable'
#before_script:
#  - npm install -g grunt-cli bower
#  - bower install
#script: grunt test
#after_success:
#  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < .tmp/coverage/report/lcov.info
